# Generated by Django 2.2 on 2019-09-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coolege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coolege_name', models.CharField(max_length=50, verbose_name='学院')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '学院',
            },
        ),
        migrations.CreateModel(
            name='Stu_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('coolege_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_table.Coolege', verbose_name='学院')),
            ],
            options={
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Stu_base_message',
            fields=[
                ('sno', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='学号')),
                ('sname', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, verbose_name='性别')),
                ('stu_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stu_table.Stu_class', verbose_name='班级')),
            ],
            options={
                'verbose_name_plural': '学生信息',
            },
        ),
    ]
