# Generated by Django 2.2 on 2019-09-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('zh_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='中文名')),
                ('eng_name', models.CharField(max_length=100, verbose_name='英文名')),
            ],
        ),
    ]
