# Generated by Django 2.2 on 2019-09-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_table', '0002_transition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transition',
            options={'verbose_name_plural': '对照表'},
        ),
    ]
