# Generated by Django 2.2 on 2019-10-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_table', '0005_auto_20190912_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stu_base_message',
            options={'ordering': ['sno'], 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterField(
            model_name='stu_class',
            name='coolege_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_name', to='stu_table.Coolege', verbose_name='学院'),
        ),
    ]
