# Generated by Django 2.2 on 2019-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('about_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='相关文件')),
                ('update_time', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否展示')),
            ],
        ),
    ]
