# Generated by Django 2.2 on 2019-09-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': '权限信息'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='user_role',
            options={'verbose_name_plural': '角色信息'},
        ),
        migrations.AddField(
            model_name='user_role',
            name='role_code',
            field=models.IntegerField(default=1, help_text='用于表示用户权限, 1 代表管理员,2 代表辅导员, 3代表班长', verbose_name='用户码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='权限描述'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='username', to='user.User_role', verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='user_role',
            name='role_description',
            field=models.TextField(max_length=200, verbose_name='角色描述'),
        ),
    ]
