# Generated by Django 2.2 on 2019-10-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190911_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '所有用户'},
        ),
    ]
